# Generated by Django 2.1.1 on 2018-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50, verbose_name='Entity Name')),
                ('gis_id', models.IntegerField(verbose_name='MC ID on GIS')),
                ('partnership_name', models.CharField(default='', max_length=50, verbose_name='Partnership Name')),
                ('video_link', models.TextField(verbose_name='Partnership Video Link')),
            ],
        ),
    ]
