# Generated by Django 2.1.1 on 2018-09-20 19:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gis_id', models.IntegerField(unique=True, verbose_name='LC ID on GIS')),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('shortname', models.CharField(max_length=50, verbose_name='Product Short Name')),
                ('gis_id', models.IntegerField(unique=True, verbose_name='Product ID on GIS')),
                ('logo', models.TextField(verbose_name='Product Logo Filename')),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='SDG Number')),
                ('name', models.CharField(max_length=50, verbose_name='SDG Name')),
                ('gis_id', models.IntegerField(unique=True, verbose_name='SDG ID on GIS')),
                ('logo', models.TextField(verbose_name='SDG Logo')),
            ],
        ),
        migrations.CreateModel(
            name='SDGLCAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LC', to_field='gis_id')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SDG', to_field='gis_id')),
            ],
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subproduct Name')),
                ('gis_id', models.IntegerField(unique=True, verbose_name='Subproduct ID on GIS')),
            ],
        ),
        migrations.CreateModel(
            name='SubproductLCAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LC', to_field='gis_id')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subproduct', to_field='gis_id')),
            ],
        ),
        migrations.RenameModel(
            old_name='EntityPartners',
            new_name='EntityPartner',
        ),
    ]
