# Generated by Django 2.1.1 on 2018-09-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lc_reference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitypartner',
            name='video_link',
            field=models.TextField(blank=True, verbose_name='Partnership Video Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Product Logo Filename'),
        ),
        migrations.AlterField(
            model_name='sdg',
            name='logo',
            field=models.TextField(blank=True, verbose_name='SDG Logo'),
        ),
    ]
