# Generated by Django 2.1.1 on 2018-09-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180920_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Product', to_field='gis_id'),
            preserve_default=False,
        ),
    ]
