# Generated by Django 2.1.1 on 2018-09-20 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLCAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product<->LC Association',
            },
        ),
        migrations.AlterModelOptions(
            name='entitypartner',
            options={'verbose_name': 'Entity Partner'},
        ),
        migrations.AlterModelOptions(
            name='lc',
            options={'verbose_name': 'LC'},
        ),
        migrations.AlterModelOptions(
            name='sdg',
            options={'verbose_name': 'SDG'},
        ),
        migrations.AlterModelOptions(
            name='sdglcassociation',
            options={'verbose_name': 'SDG<->LC Association'},
        ),
        migrations.AlterModelOptions(
            name='subproductlcassociation',
            options={'verbose_name': 'Subproduct<->LC Association'},
        ),
        migrations.RemoveField(
            model_name='lc',
            name='products',
        ),
        migrations.AlterField(
            model_name='sdglcassociation',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LC', to_field='gis_id', verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='sdglcassociation',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SDG', to_field='gis_id', verbose_name='SDG'),
        ),
        migrations.AlterField(
            model_name='subproductlcassociation',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LC', to_field='gis_id', verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='subproductlcassociation',
            name='subproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Subproduct', to_field='gis_id', verbose_name='Subproduct'),
        ),
        migrations.AddField(
            model_name='productlcassociation',
            name='lc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.LC', to_field='gis_id', verbose_name='LC'),
        ),
        migrations.AddField(
            model_name='productlcassociation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product', to_field='gis_id', verbose_name='Product'),
        ),
    ]
