# Generated by Django 2.1.1 on 2018-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180920_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlcassociation',
            name='lc',
        ),
        migrations.RemoveField(
            model_name='productlcassociation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sdglcassociation',
            name='lc',
        ),
        migrations.RemoveField(
            model_name='sdglcassociation',
            name='sdg',
        ),
        migrations.RemoveField(
            model_name='subproductlcassociation',
            name='lc',
        ),
        migrations.RemoveField(
            model_name='subproductlcassociation',
            name='subproduct',
        ),
        migrations.AddField(
            model_name='lc',
            name='products',
            field=models.ManyToManyField(to='api.Product'),
        ),
        migrations.AddField(
            model_name='lc',
            name='sdgs',
            field=models.ManyToManyField(to='api.SDG'),
        ),
        migrations.AddField(
            model_name='lc',
            name='subproducts',
            field=models.ManyToManyField(to='api.Subproduct'),
        ),
        migrations.DeleteModel(
            name='ProductLCAssociation',
        ),
        migrations.DeleteModel(
            name='SDGLCAssociation',
        ),
        migrations.DeleteModel(
            name='SubproductLCAssociation',
        ),
    ]
