# Generated by Django 2.1.1 on 2018-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180921_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lc',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
        migrations.AlterField(
            model_name='lc',
            name='sdgs',
            field=models.ManyToManyField(blank=True, to='api.SDG', verbose_name='SDG'),
        ),
        migrations.AlterField(
            model_name='lc',
            name='subproducts',
            field=models.ManyToManyField(blank=True, to='api.Subproduct'),
        ),
    ]
