# Generated by Django 2.1.1 on 2018-09-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180921_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gis_id', models.IntegerField(verbose_name='Opportunity ID on GIS')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('organization_name', models.CharField(max_length=50, verbose_name='Organization')),
                ('organization_gis_id', models.IntegerField(verbose_name='GIS ID of Organization')),
                ('picture_url', models.TextField(verbose_name='Picture URL')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('available_openings', models.IntegerField(verbose_name='Available Openings')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('updated_at', models.DateTimeField(verbose_name='Updated At')),
                ('lcid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
                ('sdg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SDG')),
                ('subproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Subproduct')),
            ],
        ),
    ]
