# Generated by Django 2.1.1 on 2018-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organization_name',
            field=models.CharField(max_length=256, verbose_name='Organization'),
        ),
    ]
