# Generated by Django 2.1.1 on 2018-09-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180925_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='lcid',
            new_name='lc',
        ),
    ]
