# Generated by Django 2.1.1 on 2018-09-26 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='focus_rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
