# Generated by Django 2.1.1 on 2018-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_focus_focus_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(max_length=256, null=True, verbose_name='Location'),
        ),
    ]
