# Generated by Django 2.1.1 on 2018-09-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180926_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3, verbose_name='ICX or OGX')),
                ('number', models.IntegerField(verbose_name='Analytic')),
                ('lc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
            ],
        ),
    ]
