# Generated by Django 2.1.1 on 2018-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_analytic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='type',
            field=models.CharField(default='icx', max_length=3, verbose_name='ICX or OGX'),
        ),
    ]
