# Generated by Django 2.1.1 on 2018-10-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180927_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='logo',
            field=models.TextField(blank=True, verbose_name='Subproduct Logo'),
        ),
    ]
