# Generated by Django 2.1.1 on 2018-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_subproduct_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50, verbose_name='Entity Name')),
                ('gis_id', models.IntegerField(verbose_name='MC ID on GIS')),
            ],
        ),
    ]
