# Generated by Django 2.1.1 on 2018-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='no_visa',
            field=models.BooleanField(default=False, verbose_name='No Visa for Brazil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Product Description'),
            preserve_default=False,
        ),
    ]
