# Generated by Django 2.1.1 on 2018-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181024_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='lc',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='City Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lc',
            name='reference_name',
            field=models.CharField(max_length=50, verbose_name='LC Name'),
        ),
    ]
