# Generated by Django 2.1.1 on 2018-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181026_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitypartner',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename (.jpg, HD)'),
        ),
        migrations.AddField(
            model_name='lc',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename (.jpg)'),
        ),
        migrations.AddField(
            model_name='lc',
            name='video_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Video Link (YouTube)'),
        ),
        migrations.AlterField(
            model_name='entitypartner',
            name='video_link',
            field=models.TextField(blank=True, verbose_name='Partnership Video Link (YouTube)'),
        ),
    ]
