# Generated by Django 2.1.1 on 2018-10-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181026_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(default='2010-01-01', verbose_name='Close Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entitypartner',
            name='video_link',
            field=models.TextField(blank=True, verbose_name='Partnership Video ID (YouTube)'),
        ),
        migrations.AlterField(
            model_name='lc',
            name='video_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Video ID (YouTube)'),
        ),
    ]
