# Generated by Django 2.1.1 on 2018-11-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181029_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DurationField()),
                ('lc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
            ],
        ),
        migrations.CreateModel(
            name='StandardsDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standards_delivery_percent', models.IntegerField()),
                ('lc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Product')),
            ],
        ),
        migrations.AddField(
            model_name='analytic',
            name='stage',
            field=models.CharField(default='APD', max_length=3, verbose_name='CF Stage'),
        ),
    ]
