# Generated by Django 2.1.1 on 2018-11-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181105_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitypartner',
            options={'verbose_name': 'Entity partner'},
        ),
        migrations.AlterModelOptions(
            name='standardsdelivery',
            options={'verbose_name_plural': 'Standards delivery'},
        ),
    ]
