# Generated by Django 2.1.1 on 2018-11-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181105_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardsdelivery',
            options={'verbose_name': 'Standard delivery percentage', 'verbose_name_plural': 'Standard delivery percentages'},
        ),
    ]
