# Generated by Django 2.1.1 on 2018-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_standardsdelivery_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='gis_id',
            field=models.IntegerField(unique=True, verbose_name='MC ID on GIS'),
        ),
        migrations.AlterField(
            model_name='entitypartner',
            name='gis_id',
            field=models.IntegerField(unique=True, verbose_name='MC ID on GIS'),
        ),
        migrations.AlterUniqueTogether(
            name='focus',
            unique_together={('lc', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='responsetime',
            unique_together={('lc', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='standardsdelivery',
            unique_together={('lc', 'product')},
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['lc'], name='api_opportu_lc_id_c98a21_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['product'], name='api_opportu_product_d96b32_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['subproduct'], name='api_opportu_subprod_982950_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['sdg'], name='api_opportu_sdg_id_b81e54_idx'),
        ),
    ]
