# Generated by Django 2.1.1 on 2018-11-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lc',
            old_name='city',
            new_name='city_name',
        ),
        migrations.AddField(
            model_name='city',
            name='mapX',
            field=models.IntegerField(default=0, verbose_name='Map X'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='mapY',
            field=models.IntegerField(default=0, verbose_name='Map Y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lc',
            name='city_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.City'),
        ),
    ]
