# Generated by Django 2.1.1 on 2018-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20181106_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='details',
            field=models.TextField(default='', verbose_name='Details (Long)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='short_desc',
            field=models.TextField(default='', verbose_name='Tagline (Short)'),
            preserve_default=False,
        ),
    ]
