# Generated by Django 2.1.1 on 2018-11-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181106_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='video_link',
            field=models.CharField(blank=True, max_length=256, verbose_name='Video ID (YouTube)'),
        ),
    ]
