# Generated by Django 2.1.1 on 2018-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20181107_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='', verbose_name='Long Description'),
            preserve_default=False,
        ),
    ]
