# Generated by Django 2.1.2 on 2018-11-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20181107_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lc',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='lc',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='lc',
            name='video_link',
        ),
    ]
