# Generated by Django 2.1.2 on 2018-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20181109_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_unaccented',
            field=models.CharField(default='', max_length=255, verbose_name='Name without special characters'),
            preserve_default=False,
        ),
    ]
