# Generated by Django 2.1.2 on 2018-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_city_name_unaccented'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opp_id', models.IntegerField(unique=True, verbose_name='Opportunity ID')),
                ('last_updated', models.DateTimeField()),
                ('opp_json', models.TextField(verbose_name='Opportunity JSON')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='analytic',
            unique_together={('lc', 'product')},
        ),
    ]
