# Generated by Django 2.1.2 on 2018-11-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_opportunitycache_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDenial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='no_visa',
        ),
        migrations.AddField(
            model_name='visadenial',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Entity', to_field='gis_id'),
        ),
        migrations.AddField(
            model_name='visadenial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product', to_field='gis_id'),
        ),
        migrations.AlterUniqueTogether(
            name='visadenial',
            unique_together={('entity', 'product')},
        ),
    ]
