# Generated by Django 2.1.2 on 2018-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20181121_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sdg',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
