# Generated by Django 2.1.2 on 2018-11-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20181126_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('logo', models.TextField(blank=True, verbose_name='Project Logo')),
                ('video_link', models.CharField(blank=True, max_length=256, verbose_name='Video ID (YouTube)')),
                ('thumbnail', models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename (.jpg)')),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sdg',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='sdg',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='sdg',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='SDG Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='sdg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SDG', to_field='number'),
        ),
    ]
