# Generated by Django 2.1.2 on 2018-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20181126_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetime',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardsdelivery',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
