# Generated by Django 2.1.2 on 2018-11-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20181126_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetime',
            name='lc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC', to_field='gis_id'),
        ),
        migrations.AlterField(
            model_name='standardsdelivery',
            name='lc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.LC', to_field='gis_id'),
        ),
    ]
