# Generated by Django 2.1.2 on 2018-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20181126_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lc',
            name='sdgs',
        ),
        migrations.AddField(
            model_name='lc',
            name='projects',
            field=models.ManyToManyField(blank=True, to='api.Project'),
        ),
    ]
