# Generated by Django 2.1.2 on 2018-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20181128_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='searchtool_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
