# Generated by Django 2.1.2 on 2018-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_city_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='unaccented_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='LC Name, without special characters / If you fill this, the LC will be accessible through this name on impactbrazil.org/lc_name'),
        ),
    ]
