# Generated by Django 2.1.2 on 2018-12-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_lc_unaccented_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='details',
            field=models.TextField(verbose_name='Details (Long - MARKDOWN is accepted here)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=256, verbose_name='Thumbnail Filename'),
        ),
    ]
