# Generated by Django 2.1.2 on 2018-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20181203_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True, verbose_name='Product Colour'),
        ),
    ]
