# Generated by Django 2.1.2 on 2018-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
